greeting : "Hi there for accounting"

---

spring:
  profiles : stage
  greeting : "Hi there for accounting stage server"

---

spring:
  profiles : dev
  greeting : "Hi there for accounting dev server"

---

spring:
  profiles : local
  greeting : "Hi there for accounting local server"
